import "./globals.css";
import { AnalyticsWrapper } from "@/components/analytics";
import Header from "@/app/Header";
import { Roboto } from "@next/font/google";
import classes from "./page.module.css";

const roboto = Roboto({
  subsets: ["latin"],
  style: "normal",
  weight: "400",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Game Base</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={`${roboto.className} ${classes.main__container}`}>
        <Header />
        {children}
        <AnalyticsWrapper />
      </body>
    </html>
  );
}
